# Generated by Django 5.0.1 on 2024-07-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_kyc_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
