# Generated by Django 5.0.1 on 2024-08-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_kyc_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active'), ('pending', 'Pending')], default='in-active', max_length=100),
        ),
    ]
