# Generated by Django 5.0.1 on 2024-08-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('failed', 'failed'), ('completed', 'completed'), ('failed', 'failed'), ('pending', 'pending'), ('processing', 'processing'), ('requested', 'requested'), ('request_processing', 'request_processing'), ('request_rejected', 'request_rejected'), ('request_sent', 'request_sent'), ('none', 'none')], default='pending', max_length=100),
        ),
    ]
